-- 测试添加和删除字段
CREATE TABLE IF NOT EXISTS user1(
    id INT UNSIGNED AUTO_INCREMENT KEY
);

-- 添加用户名字段 username VARCHAR(20)
ALTER TABLE user1 ADD username VARCHAR(20);

-- 添加密码 password VARCHAR(32) NOT NULL
ALTER TABLE user1 ADD password VARCHAR(32) NOT NULL;

-- 添加邮箱 email VARCHAR(50) NOT NULL UNIQUE
ALTER TABLE user1 ADD email VARCHAR(50) UNIQUE NOT NULL AFTER username;

ALTER TABLE user1 ADD test BOOLEAN NOT NULL DEFAULT 0 FIRST;

ALTER TABLE user1 DROP test;

-- 添加age, addr, 删除email
ALTER TABLE user1
ADD age TINYINT UNSIGNED NOT NULL DEFAULT 18,
ADD addr VARCHAR(100) NOT NULL DEFAULT 'US',
DROP email;

-- hands-on
CREATE TABLE user_test(
    id INT UNSIGNED AUTO_INCREMENT KEY,
    proName VARCHAR(20) NOT NULL UNIQUE
);

ALTER TABLE user_test
ADD price FLOAT(8) UNSIGNED NOT NULL DEFAULT 0,
ADD num INT UNSIGNED NOT NULL DEFAULT 100,
ADD test VARCHAR(50) NOT NULL FIRST,
ADD test1 CHAR(23) NOT NULL AFTER price;

ALTER TABLE user_test
DROP test,
ADD `desc` TEXT,
ADD isSale BOOL,
DROP test1;

ALTER TABLE user_test ADD (card CHAR(18) NOT NULL, phone INT UNSIGNED NOT NULL);

-- 测试添加删除默认值
CREATE TABLE user2(
    id INT UNSIGNED AUTO_INCREMENT KEY,
    username VARCHAR(20) NOT NULL,
    age TINYINT UNSIGNED NOT NULL DEFAULT 18,
    email VARCHAR(50) NOT NULL
);

ALTER TABLE user2 ALTER email SET DEFAULT 'imooc@qq.com';
ALTER TABLE user2 ALTER age DROP DEFAULT;

--
CREATE TABLE user3(
    id INT UNSIGNED AUTO_INCREMENT KEY,
    username VARCHAR(5) NOT NULL UNIQUE,
    password CHAR(32) NOT NULL,
    email VARCHAR(10) NOT NULL
);

ALTER TABLE user3
MODIFY username VARCHAR(20); -- UNIQUE属性会被保留，NOT NULL属性不会被保留

ALTER TABLE user3
CHANGE username user VARCHAR(30) NOT NULL;


CREATE TABLE user5(
    id INT UNSIGNED,
    username VARCHAR(5) NOT NULL UNIQUE,
    password CHAR(32) NOT NULL,
    email VARCHAR(10) NOT NULL
);
